# Header
menu:
  Home: /
  About: /about

# Default post title
default_post_title: Untitled

# Default post cover index page
default_cover_index: "/content/images/billiards_3D_project_01.jpg"

# Default post cover index page
default_cover_detail: "/content/images/billiards_3D_project_01.jpg"

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname:
  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics:

# Social Accounts
twitter_url:
# facebook_url: https://www.facebook.com/natasa.katirtzoglou
behance_url:
googleplus_url: mailto:anakatir@gmail.com
linkedin_url: https://linkedin.com/in/anastasia-katirtzoglou
rss_url: